# Generated by Django 5.0.2 on 2024-02-20 15:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'summoners',
            '0003_alter_rankedflex_losses_alter_rankedflex_pdls_and_more',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                (
                    'id',
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False
                    ),
                ),
                ('end_at', models.DateTimeField()),
                ('duration', models.TimeField()),
                ('queue_id', models.IntegerField()),
                ('queue_type', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='summoner',
            name='update_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='SummonerMatch',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('gold_earned', models.IntegerField()),
                ('_itens', models.CharField(max_length=100)),
                ('wards_placed', models.IntegerField()),
                ('wards_killed', models.IntegerField()),
                ('vision_wards_bought', models.IntegerField()),
                ('total_damage_dealt', models.IntegerField()),
                ('total_damage_taken', models.IntegerField()),
                ('largest_multi_kill', models.IntegerField()),
                ('level', models.IntegerField()),
                ('creep_strike', models.IntegerField()),
                ('summoner1_id', models.IntegerField()),
                ('summoner2_id', models.IntegerField()),
                (
                    'team',
                    models.CharField(
                        choices=[('B', 'Blue Side'), ('R', 'Red Side')],
                        max_length=1,
                    ),
                ),
                (
                    'position',
                    models.CharField(
                        choices=[
                            ('TOP', 'TOP'),
                            ('JG', 'JG'),
                            ('MID', 'MID'),
                            ('ADC', 'ADC'),
                            ('SUP', 'SUP'),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    'match',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='summoners.match',
                    ),
                ),
                (
                    'summoner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='summoners.summoner',
                    ),
                ),
            ],
        ),
    ]
