# Generated by Django 5.0.2 on 2024-02-20 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0004_match_summoner_update_at_summonermatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
