# Generated by Django 5.0.2 on 2024-02-20 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0005_alter_summoner_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='update_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 20, 12, 52, 33, 411908)
            ),
        ),
    ]
