# Generated by Django 5.0.2 on 2024-02-20 16:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0007_alter_summoner_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankedflex',
            name='summoner',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to='summoners.summoner',
            ),
        ),
        migrations.AlterField(
            model_name='rankedsoloduo',
            name='summoner',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to='summoners.summoner',
            ),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='update_at',
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024,
                    2,
                    20,
                    16,
                    50,
                    27,
                    254071,
                    tzinfo=datetime.timezone.utc,
                )
            ),
        ),
    ]
