# Generated by Django 5.0.2 on 2024-02-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'summoners',
            '0010_remove_summoner_account_id_summonermatch_champion_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='summonermatch',
            name='champion',
            field=models.CharField(max_length=50),
        ),
    ]
