# Generated by Django 5.0.2 on 2024-02-16 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                (
                    'id',
                    models.CharField(
                        max_length=47,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ('puuid', models.CharField(max_length=78, unique=True)),
                ('account_id', models.CharField(max_length=56, unique=True)),
                ('name', models.CharField(blank=True, max_length=16)),
                ('game_name', models.CharField(max_length=16)),
                ('tag_line', models.CharField(max_length=5)),
                ('profile_icon_id', models.IntegerField()),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RankedSoloDuo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('tier', models.CharField(max_length=10)),
                ('rank', models.CharField(max_length=2)),
                ('pdls', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                (
                    'summoner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='summoners.summoner',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RankedFlex',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('tier', models.CharField(max_length=10)),
                ('rank', models.CharField(max_length=2)),
                ('pdls', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                (
                    'summoner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='summoners.summoner',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
